
###########################################
# Mongo DB Configuration
###########################################

test:
   dbhost: localhost
   dbport: 27017
   dbname: pets_testdb
   migrations_collection: migrations
   pets_collection: pets

development:
   dbhost: localhost
   dbport: 27017
   dbname: pets_developmentdb
   migrations_collection: migrations
   pets_collection: pets